version: '3'

networks:
  f2:
    driver: bridge

services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/www
    depends_on:
      - db
    networks:
      - f2
  db:
    image: "mysql:latest"
    hostname: db
    restart: always
    networks:
      - f2
    environment:
      - MYSQL_ROOT_PASSWORD=music
      - MYSQL_DATABASE=music
      - MYSQL_USERNAME=music
      - MYSQL_PASSWORD=music
    ports:
      - '33066:3306'
    cap_add:
      - SYS_NICE
